# Setup
title: Not Pure Poole
description: A simple, beautiful, and powerful Jekyll theme for blogs
paginate: 5
permalink: pretty
cover_image: /bg.jpg



plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole
